services:
  - type: web
    name: travelroute-ai-backend
    runtime: node
    repo: https://github.com/bharadwajchakilam2003/TravelRouteAI
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OPENROUTE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: AVIATIONSTACK_API_KEY
        sync: false
      - key: OPENTRIPMAP_API_KEY
        sync: false
      - key: OILPRICE_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://travelroute-ai-frontend.onrender.com

  - type: web
    name: travelroute-ai-frontend
    runtime: static
    repo: https://github.com/bharadwajchakilam2003/TravelRouteAI
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://travelroute-ai-backend.onrender.com/api
