const CITY_AIRPORT_MAP = {
  'mumbai': 'BOM', 'bombay': 'BOM',
  'delhi': 'DEL', 'new delhi': 'DEL',
  'bangalore': 'BLR', 'bengaluru': 'BLR',
  'hyderabad': 'HYD',
  'chennai': 'MAA', 'madras': 'MAA',
  'kolkata': 'CCU', 'calcutta': 'CCU',
  'ahmedabad': 'AMD',
  'jaipur': 'JAI',
  'pune': 'PNQ',
  'goa': 'GOI',
  'kochi': 'COK', 'cochin': 'COK',
  'lucknow': 'LKO',
  'guwahati': 'GAU',
  'thiruvananthapuram': 'TRV', 'trivandrum': 'TRV',
  'chandigarh': 'IXC',
  'indore': 'IDR',
  'bhopal': 'BHO',
  'nagpur': 'NAG',
  'varanasi': 'VNS', 'banaras': 'VNS', 'kashi': 'VNS',
  'agra': 'AGR',
  'coimbatore': 'CJB',
  'mangalore': 'IXE', 'mangaluru': 'IXE',
  'vizag': 'VTZ', 'visakhapatnam': 'VTZ',
  'patna': 'PAT',
  'ranchi': 'IXR',
  'raipur': 'RPR',
  'bhubaneswar': 'BBI',
  'imphal': 'IMF',
  'shillong': 'SHL',
  'dehradun': 'DED',
  'srinagar': 'SXR',
  'jammu': 'IXJ',
  'amritsar': 'ATQ',
  'udupi': 'IXE',
  'madurai': 'IXM',
  'tiruchirappalli': 'TRZ', 'trichy': 'TRZ',
  'kalyan': 'BOM',
  'thane': 'BOM',
  'navi mumbai': 'BOM',
  'gurugram': 'DEL', 'gurgaon': 'DEL',
  'noida': 'DEL',
  'greater noida': 'DEL',
  'faridabad': 'DEL',
  'ghaziabad': 'DEL',
  'howrah': 'CCU',
  'salt lake': 'CCU',
  'secunderabad': 'HYD',
  'surat': 'STV',
  'vadodara': 'BDQ', 'baroda': 'BDQ',
  'rajkot': 'RAJ',
  'bhavnagar': 'BHU',
  'jamnagar': 'JGA',
  'porbandar': 'PBD',
  'bhuj': 'BHJ',
  'jodhpur': 'JDH',
  'udaipur': 'UDR',
  'bikaner': 'BKB',
  'jaisalmer': 'JSA',
  'gwalior': 'GWL',
  'khajuraho': 'HJR',
  'jabalpur': 'JLR',
  'kanpur': 'KNU',
  'allahabad': 'IXD', 'prayagraj': 'IXD',
  'gorakhpur': 'GOP',
  'leh': 'IXL', 'ladakh': 'IXL',
  'kullu': 'KUU',
  'dharamshala': 'DHM',
  'shimla': 'SLV',
  'port blair': 'IXZ',
  'agartala': 'IXA',
  'aizawl': 'AJL',
  'dibrugarh': 'DIB',
  'silchar': 'IXS',
  'dimapur': 'DMU',
  'gangtok': 'SXR',
  'siliguri': 'IXB',
  'bagdogra': 'IXB',
  'darjeeling': 'IXB',
  'mathura': 'AGR',
  'vrindavan': 'AGR',
  'ayodhya': 'AYJ',
  'rishikesh': 'DED',
  'haridwar': 'DED',
  'bihar sharif': 'PAT',
  'gaya': 'GAY',
  'bodh gaya': 'GAY',
  'nalanda': 'PAT',
  'muzaffarpur': 'PAT',
  'puri': 'BBI',
  'konark': 'BBI',
  'cuttack': 'BBI',
  'rourkela': 'BBI',
  'thrissur': 'COK',
  'kozhikode': 'CCJ', 'calicut': 'CCJ',
  'kannur': 'CNN',
  'alappuzha': 'COK', 'alleppey': 'COK',
  'kanyakumari': 'TRV',
  'rameswaram': 'IXM',
  'thanjavur': 'TRZ', 'tanjore': 'TRZ',
  'mahabalipuram': 'MAA',
  'kanchipuram': 'MAA',
  'vellore': 'MAA',
  'salem': 'SXV',
  'tirupati': 'TIR',
  'kurnool': 'KJ',
  'ongole': 'BBI',
  'rajahmundry': 'RJA',
  'vijayawada': 'VGA',
  'guntur': 'VGA',
  'nellore': 'TIR',
  'kadapa': 'CDP',
  'warangal': 'HYD',
  'nizamabad': 'HYD',
  'karimnagar': 'HYD',
  'belgaum': 'IXG', 'belagavi': 'IXG',
  'hubli': 'HBX', 'hubballi': 'HBX',
  'davangere': 'HBX',
  'bellary': 'BEP', 'ballari': 'BEP',
  'mysore': 'MYQ', 'mysuru': 'MYQ',
  'udupi': 'IXE',
  'dharwad': 'HBX',
  'mangaluru': 'IXE',
  'shivamogga': 'SHM', 'shimoga': 'SHM',
  'kolhapur': 'KLH',
  'aurangabad': 'IXU', 'chhatrapati sambhajinagar': 'IXU',
  'nashik': 'ISK',
  'solapur': 'SSE',
  'akola': 'AKD',
  'amravati': 'AKD',
  'nanded': 'NDC',
  'jalgaon': 'JLG',
  'ratnagiri': 'RTC',
  'sindhudurg': 'SDW',
  'dabolim': 'GOI',
  'mopa': 'GOX',
};

function getAirportCode(cityName) {
  if (!cityName) return null;
  const normalized = cityName.toLowerCase().trim();
  if (normalized.length <= 3 && /^[a-z]{3}$/.test(normalized)) {
    return normalized.toUpperCase();
  }
  return CITY_AIRPORT_MAP[normalized] || null;
}

function getNearestAirport(lat, lng) {
  const AIRPORT_COORDS = {
    'BOM': { lat: 19.0896, lng: 72.8656 },
    'DEL': { lat: 28.5562, lng: 77.1000 },
    'BLR': { lat: 13.1986, lng: 77.7066 },
    'HYD': { lat: 17.2313, lng: 78.4299 },
    'MAA': { lat: 12.9823, lng: 80.1638 },
    'CCU': { lat: 22.6508, lng: 88.4467 },
    'AMD': { lat: 23.0707, lng: 72.6346 },
    'JAI': { lat: 26.8244, lng: 75.8096 },
    'PNQ': { lat: 18.5821, lng: 73.9197 },
    'GOI': { lat: 15.3806, lng: 73.8317 },
    'COK': { lat: 10.1520, lng: 76.3990 },
    'LKO': { lat: 26.7606, lng: 80.8889 },
    'GAU': { lat: 26.1061, lng: 91.5859 },
    'TRV': { lat: 8.4841, lng: 76.9196 },
    'IXC': { lat: 30.6735, lng: 76.7888 },
    'IDR': { lat: 22.7216, lng: 75.8011 },
    'BHO': { lat: 23.2859, lng: 77.3288 },
    'NAG': { lat: 21.0900, lng: 79.0372 },
    'VNS': { lat: 25.4489, lng: 82.8593 },
    'PAT': { lat: 25.5908, lng: 85.0875 },
    'ATQ': { lat: 31.7096, lng: 74.8073 },
    'SXR': { lat: 33.9871, lng: 74.7742 },
    'IXJ': { lat: 32.6891, lng: 74.8373 },
    'BBI': { lat: 20.2961, lng: 85.8245 },
    'VTZ': { lat: 17.7212, lng: 83.2248 },
    'VGA': { lat: 16.5304, lng: 80.7968 },
    'IXR': { lat: 23.3141, lng: 85.3216 },
    'RPR': { lat: 21.1804, lng: 81.7377 },
    'UDR': { lat: 24.6174, lng: 73.9122 },
    'JDH': { lat: 26.2514, lng: 73.0505 },
    'IXG': { lat: 15.8571, lng: 74.6194 },
    'IXU': { lat: 19.8621, lng: 75.3983 },
    'CCJ': { lat: 11.1359, lng: 75.9532 },
    'COK': { lat: 10.1520, lng: 76.3990 },
  };

  let nearest = null;
  let minDist = Infinity;
  for (const [code, coord] of Object.entries(AIRPORT_COORDS)) {
    if (!coord) continue;
    const dist = Math.sqrt(Math.pow(lat - coord.lat, 2) + Math.pow(lng - coord.lng, 2));
    if (dist < minDist) {
      minDist = dist;
      nearest = code;
    }
  }
  return nearest;
}

module.exports = { getAirportCode, getNearestAirport, CITY_AIRPORT_MAP };
